apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 80  # Expose service on port 80
      targetPort: 3000  # Port your Node.js app is running on inside the pod
  type: LoadBalancer  # Depending on your environment, change the type as required
